# src: https://github.com/anmol098/waka-readme-stats
name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs at 12am (GMT/UTC)
  
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "en"                         # set language
          COMMIT_BY_ME: "False"                #"True" will make weka use your email to commit
          SHOW_LINES_OF_CODE: "False"          # show number of lines written in the whole account
          SHOW_PROFILE_VIEWS: "False"          # show number of people viewed your profile
          SHOW_COMMIT: "True"                  # show time of your commits
          SHOW_DAYS_OF_WEEK: "True"            # show activity for every day of the week
          SHOW_LANGUAGE: "True"                # show programming language stats of the week
          SHOW_OS: "False"                     # show operating system stats
          SHOW_PROJECTS: "False"               # show time consumed over each public repository
          SHOW_TIMEZONE: "False"               # show your timezone
          SHOW_EDITORS: "False"                # show IDE stats
          SHOW_LANGUAGE_PER_REPO: "False"      # show how many repositories written in a specific programming language
          SHOW_SHORT_INFO: "False"             # show some info about you
          SHOW_LOC_CHART: "False"              # count lines written for each quarter of a year
          IGNORED_REPOS: ""                    # a list of repositories to ignore, e.g: "repo1, repo2, ...etc."
          
